import { Geist, Geist_Mono, Pacifico, Playwrite_AU_NSW } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/general/Header";
import Footer from "@/components/general/Footer"
import localFont from 'next/font/local';


  const halimun = localFont({
      src: '../public/fonts/Halimun.ttf', // Adjust path as needed
      variable: '--font-halimun',
    });

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playwrite = Playwrite_AU_NSW({
  subsets: ["latin"],
  weight: ["400"], // this font may have limited weights
  variable: "--font-playwrite",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${halimun.variable} ${playwrite.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}

      >
        <Header />
        {children}
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
