export const serviceData = [
    {
        slug: "live-studio-calligraphy",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Live/studio calligraphy",
        descOne: "Experience the beauty of live calligraphy in Riyadh — where art meets performance. I specialize in Arabic and English calligraphy, creating personalized artworks right before your eyes. Whether it’s for corporate events, weddings, exhibitions, or private gatherings, live calligraphy brings a touch of elegance and culture to every occasion.",
        descTwo: "In addition, I also offer studio calligraphy services in Riyadh, where bespoke artworks are crafted with precision and passion. From custom names and wedding invitations to home décor and luxury gifts, every piece reflects the timeless beauty of calligraphy combined with modern creativity.",
        images: [
            { linkSrc: "/images/gallery/live-studio-calligraphy/01.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/02.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/03.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/04.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/05.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/06.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/07.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/08.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/09.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/10.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/11.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/12.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/13.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/14.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/15.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/16.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/17.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/18.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/19.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/20.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/21.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/22.jpeg", alt: "studio calligraphy" },
            { linkSrc: "/images/gallery/live-studio-calligraphy/23.jpeg", alt: "studio calligraphy" },
        ]

    },
    {
        slug: "bespoke-calligraphy",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Bespoke calligraphy",
        descOne: "As a bespoke calligrapher, I craft custom invitations, event signage, and place cards with care and creativity—turning words into meaningful keepsakes.",
        descTwo: "Whether in Arabic or English calligraphy, each design is tailored to your style and occasion, blending tradition with modern elegance. From wedding stationery and corporate branding to personalized gifts and home décor, my bespoke calligraphy services in Riyadh ensure every piece becomes a timeless expression of beauty and meaning.",
        images: [
            { linkSrc: "/images/gallery/bespoke-calligraphy/01.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/02.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/03.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/04.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/05.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/06.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/07.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/08.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/09.jpeg", alt: "Bespoke calligraphy" },
            { linkSrc: "/images/gallery/bespoke-calligraphy/10.jpeg", alt: "Bespoke calligraphy" },

        ]

    },
    {
        slug: "live-studio-engraving",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Live/studio Engraving",
        descOne: "As an engraving artist, I specialize in transforming everyday objects into personalized, lasting keepsakes by carefully etching names, designs, messages onto materials such as metal, wood, glass, and acrylic",
        descTwo: "I offer both live engraving for events in Riyadh and studio-based engraving services, making each piece unique and memorable. Perfect for corporate gifting, weddings, product launches, and personal celebrations, my engraving work combines artistry with precision, ensuring every detail reflects elegance, creativity, and lasting value.",
        images: [
            { linkSrc: "/images/gallery/live-studio-engraving/01.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/02.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/03.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/04.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/05.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/06.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/07.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/08.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/09.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/10.jpeg", alt: "live-studio-engraving" },
            { linkSrc: "/images/gallery/live-studio-engraving/11.jpeg", alt: "live-studio-engraving" },

        ]

    },
    {
        slug: "jewellery-illustration",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Jewellery illustration",
        descOne: "Through the delicate art of jewellery illustration, I bring intricate designs to life on paper, capturing the brilliance of gemstones, the elegance of metalwork, and the soul of each unique piece long before it becomes reality.",
        descTwo: "My jewellery illustration services in Riyadh are perfect for designers, brands, and individuals who want to visualize their creations with clarity and elegance. From detailed sketches and digital renderings to custom concept drawings, I translate ideas into stunning visuals that highlight craftsmanship, style, and individuality before they are brought to life.",
        images: [
            { linkSrc: "/images/gallery/jewellery-illustration/01.jpeg", alt: "Jewellery illustration" },
            { linkSrc: "/images/gallery/jewellery-illustration/02.jpeg", alt: "Jewellery illustration" },
            { linkSrc: "/images/gallery/jewellery-illustration/03.webp", alt: "Jewellery illustration" },
            { linkSrc: "/images/gallery/jewellery-illustration/04.jpeg", alt: "Jewellery illustration" },
            { linkSrc: "/images/gallery/jewellery-illustration/05.jpeg", alt: "Jewellery illustration" },
            { linkSrc: "/images/gallery/jewellery-illustration/06.jpeg", alt: "Jewellery illustration" },

        ]

    },
    {
        slug: "heat-foiling",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Heat foiling",
        descOne: "Bring elegance and luxury to your products with professional heat foiling in Riyadh. From Arabic and English calligraphy to logos and custom designs, I create stunning metallic impressions on invitations, leather goods, stationery, packaging, and personalized gifts.",
        descTwo: "Perfect for weddings, corporate events, and luxury branding, my heat foiling services offer a premium finish in gold, silver, and colored foils. Each piece is crafted with precision, giving your artwork or product a timeless, high-quality look.",
        images: [
            { linkSrc: "/images/gallery/heat-foiling/01.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/02.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/03.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/04.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/05.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/06.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/07.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/08.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/09.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/10.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/11.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/12.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/13.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/14.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/15.jpeg", alt: "Heat foiling" },
            { linkSrc: "/images/gallery/heat-foiling/16.jpeg", alt: "Heat foiling" },

        ]

    },
    {
        slug: "product-painting",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Product painting",
        descOne: "Enhance your everyday items with custom product painting in Riyadh. I specialize in transforming bottles, accessories, décor items, and gifts into one-of-a-kind artworks using Arabic and English calligraphy, abstract designs, and personalized patterns.",
        descTwo: "Whether for special occasions, corporate gifting, or personal use, my hand-painted products bring uniqueness, creativity, and cultural elegance to your collection. Each piece is carefully crafted to reflect your style and story.",
        images: [
            { linkSrc: "/images/gallery/product-painting/01.webp", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/02.webp", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/03.webp", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/04.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/05.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/06.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/07.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/08.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/09.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/10.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/11.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/12.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/13.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/14.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/15.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/16.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/17.jpeg", alt: "Product painting" },
            { linkSrc: "/images/gallery/product-painting/18.png", alt: "Product painting" },

        ]

    },
    {
        slug: "leather-painting",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Leather painting",
        descOne: "I specialize in creating one-of-a-kind hand-painted leather pieces, transforming ordinary leather items like bags, wallets, jackets, and shoes into beautiful, personalized works of art.",
        descTwo: "Each design is crafted with care using durable, high-quality paints that preserve both beauty and longevity. Whether for personal use, gifting, or branding, my leather painting services in Riyadh add a unique touch of elegance and individuality, turning everyday leather goods into timeless artistic statements.",
        images: [
            { linkSrc: "/images/gallery/leather-painting/01.webp", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/02.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/04.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/05.webp", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/06.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/07.webp", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/08.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/09.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/10.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/11.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/12.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/13.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/14.jpeg", alt: "Leather painting" },
            { linkSrc: "/images/gallery/leather-painting/15.jpeg", alt: "Leather painting" },


        ]

    },
    {
        slug: "mural-painting",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Mural painting",
        descOne: "I collaborate with clients to design and paint impactful murals that reflect their vision, enhance their space, and connect with their audience.",
        descTwo: "From homes and offices to cafés, restaurants, and event spaces, my mural painting services in Riyadh bring walls to life with vibrant colors, cultural motifs, and modern designs. Each mural is carefully crafted to transform ordinary spaces into inspiring environments that leave a lasting impression.",
        images: [
            { linkSrc: "/images/gallery/mural-painting/01.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/02.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/03.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/04.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/05.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/06.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/07.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/08.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/09.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/10.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/11.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/12.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/13.jpeg", alt: "Mural painting" },
            { linkSrc: "/images/gallery/mural-painting/14.jpeg", alt: "Mural painting" },



        ]

    },
    {
        slug: "tote-bag-live",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Tote bag live",
        descOne: "I transform simple, everyday tote bags into personalized pieces of art using custom designs, names, quotes, and graphics — perfect for gifting, branding, or simply carrying a bit of your personality wherever you go.",
        descTwo: "With live tote bag painting in Riyadh, I also create interactive experiences at events, exhibitions, and brand activations, where guests can watch their tote bags being customized in real time. Each piece becomes a memorable keepsake, blending creativity, personalization, and functionality.",
        images: [
            { linkSrc: "/images/gallery/tote-bag/01.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/02.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/03.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/04.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/05.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/06.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/07.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/08.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/09.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/10.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/11.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/12.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/13.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/14.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/15.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/16.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/17.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/18.jpeg", alt: "Tote bag live" },
            { linkSrc: "/images/gallery/tote-bag/19.jpeg", alt: "Tote bag live" },
        ]
    },
    {
        slug: "artwork-customisation",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Artwork customisation",
        descOne: "I specialize in creating personalized calligraphy, portraits, and abstract designs that reflect your unique taste, story, and cultural identity. From family names and inspirational quotes to bespoke home décor, every piece is crafted to match your vision.",
        descTwo: "Perfect for gifts, events, and interior décor, my artwork customisation services blend traditional artistry with modern creativity. Each creation is designed with care and precision, ensuring you receive an artwork that is meaningful, elegant, and timeless.",
        images: [
            { linkSrc: "/images/gallery/artwork-customisation/01.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/02.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/03.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/04.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/05.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/06.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/07.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/08.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/09.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/10.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/11.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/12.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/13.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/14.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/15.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/16.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/17.jpeg", alt: "Artwork customisation" },
            { linkSrc: "/images/gallery/artwork-customisation/18.jpeg", alt: "Artwork customisation" },
            
        ]
    },
    {
        slug: "beads-making",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Beads making",
        descOne: "Each bracelet is carefully crafted using high-quality beads. Beads, colors, and creativity — I turn them into beautiful bracelets, keychains and many more",
        descTwo: "My handmade bead accessories in Riyadh are designed to reflect style, tradition, and individuality. From custom bracelets and necklaces to decorative keychains, each piece is a blend of artistry and craftsmanship, making them perfect for personal use, thoughtful gifts, or event giveaways.",
        images: [
            { linkSrc: "/images/gallery/beads-making/01.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/02.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/03.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/04.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/05.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/06.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/07.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/08.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/09.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/10.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/11.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/12.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/13.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/14.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/15.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/16.jpeg", alt: "Beads making" },
            { linkSrc: "/images/gallery/beads-making/17.jpeg", alt: "Beads making" },
            
        ]
    },
    {
        slug: "hand-embroidery-work",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Hand Embroidery work",
        descOne: "Each embroidered creation is a unique blend of skill and imagination, carefully crafted by hand to bring color, texture, and life to fabric",
        descTwo: "From traditional patterns to modern custom designs, my hand embroidery services in Riyadh add elegance and personality to garments, accessories, and home décor. Perfect for personal gifts, weddings, and bespoke fashion, each piece reflects timeless artistry stitched with care and creativity.",
        images: [
            { linkSrc: "/images/gallery/hand-embroidery/01.webp", alt: "Hand Embroidery work" },
            { linkSrc: "/images/gallery/hand-embroidery/02.webp", alt: "Hand Embroidery work" },
            { linkSrc: "/images/gallery/hand-embroidery/03.webp", alt: "Hand Embroidery work" },         
            
        ]
    },
    {
        slug: "silhouette-arts",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Silhouette arts",
        descOne: "I specialize in silhouette art, transforming everyday moments into timeless black-and-white expressions.",
        descTwo: "My silhouette art services in Riyadh are perfect for portraits, weddings, events, and personalized gifts, capturing elegance in the simplest of forms. Each piece is hand-crafted or digitally designed with precision, creating meaningful keepsakes that never go out of style.",
        images: [
            { linkSrc: "/images/gallery/silhouette-art/01.jpeg", alt: "Silhouette arts" },
            { linkSrc: "/images/gallery/silhouette-art/02.jpeg", alt: "Silhouette arts" },
            { linkSrc: "/images/gallery/silhouette-art/03.jpeg", alt: "Silhouette arts" },         
            { linkSrc: "/images/gallery/silhouette-art/04.jpeg", alt: "Silhouette arts" },         
            { linkSrc: "/images/gallery/silhouette-art/05.jpeg", alt: "Silhouette arts" },         
            
        ]
    },
    {
        slug: "origami-work",
        bannerUrl: "/images/dynamic-my-work.png",
        title: "Origami work",
        descOne: "I create art through the delicate folds of paper—this is my journey in origami.",
        descTwo: "From decorative pieces and event décor to custom gifts and workshops, my origami services in Riyadh showcase the beauty of paper transformed into art. Each fold carries precision, patience, and creativity, turning simple sheets into meaningful creations that inspire wonder.",
        images: [
            { linkSrc: "/images/gallery/origami-work/01.jpeg", alt: "Origami work" },
            { linkSrc: "/images/gallery/origami-work/02.jpeg", alt: "Origami work" },
            { linkSrc: "/images/gallery/origami-work/03.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/04.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/05.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/06.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/07.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/08.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/09.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/10.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/11.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/12.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/13.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/14.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/15.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/16.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/17.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/18.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/19.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/20.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/21.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/22.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/23.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/24.jpeg", alt: "Origami work" },         
            { linkSrc: "/images/gallery/origami-work/25.jpeg", alt: "Origami work" },         
            
        ]
    },
]